name: Swift CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Available Xcode Versions
        run: ls /Applications | grep Xcode

      - name: Set Xcode Version to 16.1
        run: sudo xcode-select -switch /Applications/Xcode_16.1.0.app

      - name: Verify Xcode Version
        run: xcodebuild -version

      - name: Resolve Dependencies
        run: xcodebuild -resolvePackageDependencies
        working-directory: ./Smeem-iOS

      - name: Create Debug.xcconfig
        run: echo "${{ secrets.DEBUG_CONFIG }}" > ./Smeem-iOS/Debug.xcconfig

      - name: Build and Test
        run: xcodebuild clean test -project Smeem-iOS/Smeem-iOS.xcodeproj -scheme Smeem-Dev -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'

      # 성공 시 Discord 알림
      - name: Notify Discord on success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"username": "GitHub Actions", "content": "✅ Build succeeded for branch `${{ github.ref_name }}`."}' \
            ${{ secrets.DISCORD_WEBHOOK_URL_DEV }}

      # 실패 시 Discord 알림
      - name: Notify Discord on failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"username": "GitHub Actions", "content": "❌ Build failed for branch `${{ github.ref_name }}`. Check logs for details."}' \
            ${{ secrets.DISCORD_WEBHOOK_URL_DEV }}
