# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_16.app
    - name: List available devices
      run: xcrun simctl list devices
    - name: Resolve Dependencies
      run: xcodebuild -resolvePackageDependencies
      working-directory: ./Smeem-iOS
    - name: Create Debug.xcconfig
      run: echo "${{ secrets.DEBUG_CONFIG }}" > ./Smeem-iOS/Debug.xcconfig
    - name: Build
      run: xcodebuild build -project Smeem-iOS/Smeem-iOS.xcodeproj -scheme Smeem-Dev -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=17.2'
