# workflow 의 이름
name: Run Test

on:
  # 트리거 조건 push 하거나 PR 올렸을 때 하단 jobs 실행
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# workflow의 실행은 하나 이상의 job으로 구성 됨
jobs:
  # 이 workflow 는 "build" 라는 single job 으로 구성
  build:
    # job이 실행될 환경 - 최신 mac os
    runs-on: macos-latest

    # Step은 job의 일부로 실행될 일련의 task들을 나타냄
    steps:
    # uses 키워드를 통해 Github Actions에서 기본으로 제공하는 액션을 사용 가능. 아래 액션은 repository 에 체크아웃하는 것
    - uses: actions/checkout@v2
    # shell 이용해서 하나의 command 수행
    - name: Start xcode build 🛠
      run: |
        xcodebuild clean test -project Smeem-iOS/Smeem-iOS.xcodeproj -scheme Smeem-Dev -destination 'platform=iOS Simulator,name=iPhone 13 mini,OS=15'
